# Generated by Django 2.1.1 on 2020-03-20 06:36

from django.db import migrations
from webapi.models import User, Profile


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    def add_profiles_to_existing_users(apps, schema_editor):
        for user in User.objects.all():
            Profile.objects.get_or_create(user=user)

    operations = [
        migrations.RunPython(add_profiles_to_existing_users),
    ]
