# Generated by Django 5.1.1 on 2024-09-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='score',
            name='groups',
            field=models.ManyToManyField(related_name='scores', to='playapp.group'),
        ),
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('price_modifier', models.FloatField()),
                ('items', models.ManyToManyField(related_name='price_groups', to='playapp.item')),
            ],
        ),
    ]
