# Generated by Django 5.1.1 on 2024-09-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playapp', '0002_item_alter_score_groups_pricegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pricegroup',
            name='price_modifier',
            field=models.FloatField(default=0),
        ),
    ]
