# Generated by Django 2.1.1 on 2020-03-20 06:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamestate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.UUIDField()),
                ('board_width', models.IntegerField(default=0)),
                ('board_height', models.IntegerField(default=0)),
                ('location', models.IntegerField(default=0)),
                ('game_over', models.BooleanField(default=True)),
                ('player1_wins', models.BooleanField(default=False)),
                ('rocks_awarded', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
                ('player1_active', models.BooleanField(default=True)),
                ('board_tiles', models.CharField(max_length=1000, validators=[django.core.validators.int_list_validator])),
                ('player1_rocks', models.CharField(max_length=8, validators=[django.core.validators.int_list_validator])),
                ('player2_rocks', models.CharField(max_length=8, validators=[django.core.validators.int_list_validator])),
                ('player1_rock_x_coords', models.CharField(max_length=8, validators=[django.core.validators.int_list_validator])),
                ('player1_rock_y_coords', models.CharField(max_length=8, validators=[django.core.validators.int_list_validator])),
                ('player2_rock_x_coords', models.CharField(max_length=8, validators=[django.core.validators.int_list_validator])),
                ('player2_rock_y_coords', models.CharField(max_length=8, validators=[django.core.validators.int_list_validator])),
                ('player1_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_player1_gamestates', to=settings.AUTH_USER_MODEL)),
                ('player2_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_player2_gamestates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=10000, validators=[django.core.validators.int_list_validator])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
