# Generated by Django 2.1.1 on 2020-03-22 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='player1_rock_x_coords',
            field=models.CharField(max_length=80, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player1_rock_y_coords',
            field=models.CharField(max_length=80, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player1_rocks',
            field=models.CharField(max_length=80, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player2_rock_x_coords',
            field=models.CharField(max_length=80, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player2_rock_y_coords',
            field=models.CharField(max_length=80, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player2_rocks',
            field=models.CharField(max_length=80, validators=[django.core.validators.int_list_validator]),
        ),
    ]
