# Generated by Django 2.1.1 on 2020-03-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_auto_20200321_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestate',
            name='player1_active',
        ),
        migrations.AddField(
            model_name='gamestate',
            name='turns_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='valid_action_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
    ]
