# Generated by Django 2.1.1 on 2020-03-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_auto_20200321_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestate',
            old_name='game_id',
            new_name='game_uuid',
        ),
    ]
