# Generated by Django 2.1.1 on 2020-03-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0005_auto_20200322_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestate',
            old_name='player1_rock_x_coords',
            new_name='player1_rocks_x_coords',
        ),
        migrations.RenameField(
            model_name='gamestate',
            old_name='player1_rock_y_coords',
            new_name='player1_rocks_y_coords',
        ),
        migrations.RenameField(
            model_name='gamestate',
            old_name='player2_rock_x_coords',
            new_name='player2_rocks_x_coords',
        ),
        migrations.RenameField(
            model_name='gamestate',
            old_name='player2_rock_y_coords',
            new_name='player2_rocks_y_coords',
        ),
    ]
