# Generated by Django 2.1.1 on 2020-03-26 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0006_auto_20200322_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='turn_history',
            field=models.CharField(default='', max_length=10000, validators=[django.core.validators.int_list_validator]),
        ),
    ]
