# Generated by Django 2.1.1 on 2020-03-28 00:13

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0007_gamestate_turn_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='player1_square_count_per_rock',
            field=models.CharField(default='', max_length=80, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player2_square_count_per_rock',
            field=models.CharField(default='', max_length=80, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player1_rocks_x_coords',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^(-)?\\d+(?:,(-)?\\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player1_rocks_y_coords',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^(-)?\\d+(?:,(-)?\\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player2_rocks_x_coords',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^(-)?\\d+(?:,(-)?\\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player2_rocks_y_coords',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^(-)?\\d+(?:,(-)?\\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
